services:
  # cros-todolist-db:
  # container_name: cros-todolist
  # image: mcr.microsoft.com/mssql/server:2022-latest
  # ports:
  #   - '1433:1433'
  # environment:
  #   MSSQL_SA_PASSWORD: 'CrosTodolist1.0'
  #   ACCEPT_EULA: 'Y'
  # mem_limit: 1.5G
  # cpus: 0.50
  mockp-db:
    container_name: cros-todolist-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: crostodolist
      POSTGRES_PASSWORD: crostodolist
      POSTGRES_DB: cros-todolist
